# Generated by Django 5.2.2 on 2025-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
